// Wingspan Approach — Aviation Question Bank
// Organized by topic & difficulty

const QUESTION_BANK = [
  // ═══════════════════════════════════════════
  // AIR NAVIGATION
  // ═══════════════════════════════════════════
  // Easy
  { topic:"Air Navigation", difficulty:"easy", type:"mcq", question:"What does GPS stand for?", options:["Global Positioning System","General Pilot System","Ground Position Signal","Global Pilot Service"], answer:"Global Positioning System", explanation:"GPS stands for Global Positioning System, a satellite-based navigation system." },
  { topic:"Air Navigation", difficulty:"easy", type:"mcq", question:"True North is indicated by which reference?", options:["Geographic North Pole","Magnetic North Pole","Grid North","Compass North"], answer:"Geographic North Pole", explanation:"True North refers to the direction towards the Geographic North Pole." },
  { topic:"Air Navigation", difficulty:"easy", type:"truefalse", question:"Latitude lines run east to west on a map.", answer:"True", explanation:"Latitude lines (parallels) run east-west, measuring north-south position." },
  { topic:"Air Navigation", difficulty:"easy", type:"truefalse", question:"One degree of latitude equals approximately 60 nautical miles.", answer:"True", explanation:"One degree of latitude is approximately 60 NM (111 km)." },
  { topic:"Air Navigation", difficulty:"easy", type:"mcq", question:"What is the unit of distance commonly used in aviation?", options:["Nautical Mile","Kilometer","Statute Mile","Meter"], answer:"Nautical Mile", explanation:"Aviation uses nautical miles (NM) as the standard unit of distance." },
  { topic:"Air Navigation", difficulty:"easy", type:"short", question:"What instrument displays the aircraft's magnetic heading?", answer:"Magnetic compass", explanation:"The magnetic compass indicates the aircraft's heading relative to magnetic north." },
  // Medium
  { topic:"Air Navigation", difficulty:"medium", type:"mcq", question:"What is the variation between True North and Magnetic North called?", options:["Magnetic Declination","Deviation","Drift","Bearing Error"], answer:"Magnetic Declination", explanation:"Magnetic declination (or variation) is the angle between true and magnetic north." },
  { topic:"Air Navigation", difficulty:"medium", type:"mcq", question:"A VOR station transmits on which frequency band?", options:["VHF (108–117.95 MHz)","HF (3–30 MHz)","UHF (300 MHz–3 GHz)","LF (30–300 kHz)"], answer:"VHF (108–117.95 MHz)", explanation:"VOR operates in the VHF band between 108.0 and 117.95 MHz." },
  { topic:"Air Navigation", difficulty:"medium", type:"truefalse", question:"An NDB uses VHF radio signals for navigation.", answer:"False", explanation:"NDB (Non-Directional Beacon) uses LF/MF frequencies, not VHF." },
  { topic:"Air Navigation", difficulty:"medium", type:"mcq", question:"What does DME measure?", options:["Slant range distance","Altitude","Ground speed","Wind direction"], answer:"Slant range distance", explanation:"DME measures the slant range distance between the aircraft and the ground station." },
  { topic:"Air Navigation", difficulty:"medium", type:"short", question:"What is the name of the line on a Mercator chart that crosses all meridians at a constant angle?", answer:"Rhumb line", explanation:"A rhumb line (loxodrome) crosses all meridians at the same angle." },
  { topic:"Air Navigation", difficulty:"medium", type:"mcq", question:"Which chart projection is most commonly used for en-route navigation?", options:["Lambert Conformal Conic","Mercator","Polar Stereographic","Gnomonic"], answer:"Lambert Conformal Conic", explanation:"Lambert Conformal Conic projection is standard for en-route aeronautical charts." },
  // Hard
  { topic:"Air Navigation", difficulty:"hard", type:"mcq", question:"On a Lambert Conformal Conic chart, a straight line approximates a:", options:["Great Circle","Rhumb Line","Isogonal","Agonic Line"], answer:"Great Circle", explanation:"On a Lambert chart, straight lines closely approximate great circle routes." },
  { topic:"Air Navigation", difficulty:"hard", type:"mcq", question:"What is the convergency factor on a Lambert chart at standard parallels 30°N and 60°N?", options:["0.78","0.50","0.87","0.65"], answer:"0.78", explanation:"Convergency factor = sin(mean parallel). sin(45°) ≈ 0.707, but standard parallels' mean gives ~0.78." },
  { topic:"Air Navigation", difficulty:"hard", type:"truefalse", question:"RNAV approaches can only be flown with GPS equipment.", answer:"False", explanation:"RNAV can use DME/DME, INS, or GPS-based systems." },
  { topic:"Air Navigation", difficulty:"hard", type:"short", question:"What is the term for the angular difference between magnetic heading and compass heading?", answer:"Deviation", explanation:"Deviation is caused by the aircraft's own magnetic fields affecting the compass." },

  // ═══════════════════════════════════════════
  // METEOROLOGY
  // ═══════════════════════════════════════════
  // Easy
  { topic:"Meteorology", difficulty:"easy", type:"mcq", question:"What is the standard atmospheric pressure at sea level?", options:["1013.25 hPa","1000 hPa","980 hPa","1020 hPa"], answer:"1013.25 hPa", explanation:"The ISA standard sea-level pressure is 1013.25 hPa (29.92 inHg)." },
  { topic:"Meteorology", difficulty:"easy", type:"mcq", question:"What is the ISA standard temperature at sea level?", options:["15°C","20°C","0°C","25°C"], answer:"15°C", explanation:"ISA standard sea-level temperature is 15°C (59°F)." },
  { topic:"Meteorology", difficulty:"easy", type:"truefalse", question:"Cumulonimbus clouds are associated with thunderstorms.", answer:"True", explanation:"Cb clouds produce thunderstorms, heavy rain, lightning, turbulence, and hail." },
  { topic:"Meteorology", difficulty:"easy", type:"mcq", question:"What type of cloud is flat and layered?", options:["Stratus","Cumulus","Cirrus","Nimbus"], answer:"Stratus", explanation:"Stratus clouds are low-level, flat, uniform layered clouds." },
  { topic:"Meteorology", difficulty:"easy", type:"short", question:"What does METAR stand for?", answer:"Meteorological Aerodrome Report", explanation:"METAR is a routine weather observation report for an aerodrome." },
  { topic:"Meteorology", difficulty:"easy", type:"truefalse", question:"Wind is always reported in true direction in METARs.", answer:"True", explanation:"METAR wind direction is given relative to true north." },
  // Medium
  { topic:"Meteorology", difficulty:"medium", type:"mcq", question:"At what rate does temperature decrease in the ISA standard atmosphere?", options:["1.98°C per 1000 ft","2.5°C per 1000 ft","3°C per 1000 ft","1°C per 1000 ft"], answer:"1.98°C per 1000 ft", explanation:"ISA lapse rate is approximately 1.98°C (or ~2°C) per 1000 ft up to the tropopause." },
  { topic:"Meteorology", difficulty:"medium", type:"mcq", question:"What weather phenomenon is caused by the orographic lifting of moist air?", options:["Orographic rain","Convective rain","Frontal rain","Cyclonic rain"], answer:"Orographic rain", explanation:"When moist air is forced upward by terrain, it cools and produces orographic precipitation." },
  { topic:"Meteorology", difficulty:"medium", type:"truefalse", question:"A cold front typically moves faster than a warm front.", answer:"True", explanation:"Cold fronts are steeper and move about 1.5x faster than warm fronts." },
  { topic:"Meteorology", difficulty:"medium", type:"mcq", question:"In the Northern Hemisphere, wind flows around a low pressure system in which direction?", options:["Counter-clockwise","Clockwise","Straight inward","Straight outward"], answer:"Counter-clockwise", explanation:"Coriolis effect causes counter-clockwise flow around lows in the Northern Hemisphere." },
  { topic:"Meteorology", difficulty:"medium", type:"short", question:"What is the name of the boundary between two different air masses?", answer:"Front", explanation:"A front is the boundary zone between two air masses of different temperature/humidity." },
  { topic:"Meteorology", difficulty:"medium", type:"mcq", question:"What does TAF stand for?", options:["Terminal Aerodrome Forecast","Total Altitude Forecast","Temporary Aviation Forecast","True Air Flow"], answer:"Terminal Aerodrome Forecast", explanation:"TAF is a weather forecast for a specific aerodrome, valid for 24-30 hours." },
  // Hard
  { topic:"Meteorology", difficulty:"hard", type:"mcq", question:"What type of icing is most dangerous to aircraft?", options:["Clear ice","Rime ice","Mixed ice","Frost"], answer:"Clear ice", explanation:"Clear (glaze) ice is the most dangerous—it's heavy, hard to detect, and difficult to remove." },
  { topic:"Meteorology", difficulty:"hard", type:"mcq", question:"The tropopause in ISA conditions is at approximately:", options:["36,090 ft","40,000 ft","25,000 ft","45,000 ft"], answer:"36,090 ft", explanation:"The ISA tropopause is at 36,090 ft (11,000 m) where temperature stabilizes at -56.5°C." },
  { topic:"Meteorology", difficulty:"hard", type:"truefalse", question:"Microbursts can produce wind shear with speed changes exceeding 100 knots.", answer:"True", explanation:"Microbursts can create wind shear of 100+ knots over very short distances, extremely hazardous." },
  { topic:"Meteorology", difficulty:"hard", type:"short", question:"Name the phenomenon where temperature increases with altitude instead of decreasing.", answer:"Temperature inversion", explanation:"A temperature inversion traps pollutants and can cause reduced visibility and turbulence." },

  // ═══════════════════════════════════════════
  // AIR REGULATIONS
  // ═══════════════════════════════════════════
  // Easy
  { topic:"Air Regulations", difficulty:"easy", type:"mcq", question:"Which organization sets international civil aviation standards?", options:["ICAO","FAA","EASA","IATA"], answer:"ICAO", explanation:"ICAO (International Civil Aviation Organization) sets global aviation standards." },
  { topic:"Air Regulations", difficulty:"easy", type:"mcq", question:"In India, which body is responsible for civil aviation regulation?", options:["DGCA","AAI","BCAS","MoCA"], answer:"DGCA", explanation:"DGCA (Directorate General of Civil Aviation) regulates civil aviation in India." },
  { topic:"Air Regulations", difficulty:"easy", type:"truefalse", question:"The pilot-in-command has final authority for the safe operation of the flight.", answer:"True", explanation:"The PIC has ultimate responsibility and authority for the aircraft's safe operation." },
  { topic:"Air Regulations", difficulty:"easy", type:"mcq", question:"What is the minimum age to obtain a Private Pilot License (PPL)?", options:["17 years","16 years","18 years","21 years"], answer:"17 years", explanation:"The minimum age for a PPL is 17 years (16 for solo in some countries)." },
  { topic:"Air Regulations", difficulty:"easy", type:"short", question:"What does VFR stand for?", answer:"Visual Flight Rules", explanation:"VFR means Visual Flight Rules, where pilots navigate by visual reference to the ground." },
  { topic:"Air Regulations", difficulty:"easy", type:"truefalse", question:"IFR stands for Instrument Flying Rules.", answer:"False", explanation:"IFR stands for Instrument Flight Rules (not Flying Rules)." },
  // Medium
  { topic:"Air Regulations", difficulty:"medium", type:"mcq", question:"What is the minimum flight visibility for VFR flight in controlled airspace (Class C)?", options:["5 km","3 km","8 km","1.5 km"], answer:"5 km", explanation:"VFR in Class C airspace requires minimum 5 km flight visibility." },
  { topic:"Air Regulations", difficulty:"medium", type:"mcq", question:"ICAO Annex 2 deals with:", options:["Rules of the Air","Personnel Licensing","Airworthiness","Aerodromes"], answer:"Rules of the Air", explanation:"Annex 2 covers the Rules of the Air applicable over the high seas and territories." },
  { topic:"Air Regulations", difficulty:"medium", type:"truefalse", question:"Squawk code 7700 indicates a hijack situation.", answer:"False", explanation:"7700 is the emergency code. 7500 is for hijack/unlawful interference." },
  { topic:"Air Regulations", difficulty:"medium", type:"mcq", question:"What transponder code indicates radio communication failure?", options:["7600","7700","7500","1200"], answer:"7600", explanation:"Squawk 7600 indicates radio/communication failure." },
  { topic:"Air Regulations", difficulty:"medium", type:"short", question:"What does NOTAM stand for?", answer:"Notice to Airmen", explanation:"NOTAMs provide important information about hazards or changes along a flight route." },
  { topic:"Air Regulations", difficulty:"medium", type:"mcq", question:"Which ICAO Annex deals with Personnel Licensing?", options:["Annex 1","Annex 2","Annex 6","Annex 8"], answer:"Annex 1", explanation:"ICAO Annex 1 covers Personnel Licensing requirements." },
  // Hard
  { topic:"Air Regulations", difficulty:"hard", type:"mcq", question:"Under ICAO rules, the minimum vertical separation in RVSM airspace is:", options:["1000 ft","2000 ft","500 ft","1500 ft"], answer:"1000 ft", explanation:"RVSM (Reduced Vertical Separation Minimum) allows 1000 ft separation between FL290-FL410." },
  { topic:"Air Regulations", difficulty:"hard", type:"truefalse", question:"Aircraft operating in RVSM airspace must have two independent altitude measurement systems.", answer:"True", explanation:"RVSM-approved aircraft require two independent altimetry systems for safety." },
  { topic:"Air Regulations", difficulty:"hard", type:"mcq", question:"What is the purpose of ICAO Annex 13?", options:["Aircraft Accident Investigation","Aeronautical Charts","Security","Air Traffic Services"], answer:"Aircraft Accident Investigation", explanation:"Annex 13 establishes international standards for aircraft accident/incident investigation." },
  { topic:"Air Regulations", difficulty:"hard", type:"short", question:"What does ETOPS stand for?", answer:"Extended Twin-engine Operations", explanation:"ETOPS allows twin-engine aircraft to fly long routes far from diversion airports." },

  // ═══════════════════════════════════════════
  // AIRCRAFT SYSTEMS
  // ═══════════════════════════════════════════
  // Easy
  { topic:"Aircraft Systems", difficulty:"easy", type:"mcq", question:"Which flight control surface controls pitch?", options:["Elevator","Ailerons","Rudder","Flaps"], answer:"Elevator", explanation:"The elevator (on the horizontal stabilizer) controls pitch (nose up/down)." },
  { topic:"Aircraft Systems", difficulty:"easy", type:"mcq", question:"Ailerons control which axis of movement?", options:["Roll (longitudinal)","Pitch (lateral)","Yaw (vertical)","Thrust"], answer:"Roll (longitudinal)", explanation:"Ailerons control roll about the longitudinal axis." },
  { topic:"Aircraft Systems", difficulty:"easy", type:"truefalse", question:"The rudder controls the yaw movement of an aircraft.", answer:"True", explanation:"The rudder on the vertical stabilizer controls yaw (left/right movement of the nose)." },
  { topic:"Aircraft Systems", difficulty:"easy", type:"mcq", question:"What does the altimeter measure?", options:["Altitude","Airspeed","Vertical speed","Heading"], answer:"Altitude", explanation:"The altimeter measures the aircraft's altitude above a reference pressure level." },
  { topic:"Aircraft Systems", difficulty:"easy", type:"short", question:"What is the purpose of flaps on an aircraft?", answer:"To increase lift and drag for slower flight speeds", explanation:"Flaps increase the wing's camber and area, allowing lower approach speeds." },
  { topic:"Aircraft Systems", difficulty:"easy", type:"truefalse", question:"Jet engines work on the principle of Newton's Third Law of Motion.", answer:"True", explanation:"Jet engines expel exhaust gases backward, producing forward thrust (action-reaction)." },
  // Medium
  { topic:"Aircraft Systems", difficulty:"medium", type:"mcq", question:"What is the function of the pitot-static system?", options:["Measures airspeed, altitude, and vertical speed","Measures engine temperature","Controls fuel flow","Manages hydraulic pressure"], answer:"Measures airspeed, altitude, and vertical speed", explanation:"The pitot-static system provides data for the ASI, altimeter, and VSI." },
  { topic:"Aircraft Systems", difficulty:"medium", type:"mcq", question:"In a hydraulic system, what converts hydraulic pressure into mechanical force?", options:["Actuator","Pump","Reservoir","Filter"], answer:"Actuator", explanation:"Hydraulic actuators convert fluid pressure into linear or rotary mechanical motion." },
  { topic:"Aircraft Systems", difficulty:"medium", type:"truefalse", question:"A turbofan engine is more fuel-efficient than a turbojet at subsonic speeds.", answer:"True", explanation:"Turbofans have a higher bypass ratio, making them more efficient at subsonic cruise speeds." },
  { topic:"Aircraft Systems", difficulty:"medium", type:"mcq", question:"What instrument shows aircraft pitch and bank attitude?", options:["Attitude Indicator (AI)","Heading Indicator","Turn Coordinator","Altimeter"], answer:"Attitude Indicator (AI)", explanation:"The Attitude Indicator (artificial horizon) shows pitch and bank angles." },
  { topic:"Aircraft Systems", difficulty:"medium", type:"short", question:"What does TCAS stand for?", answer:"Traffic Collision Avoidance System", explanation:"TCAS provides traffic advisories and resolution advisories to prevent mid-air collisions." },
  { topic:"Aircraft Systems", difficulty:"medium", type:"mcq", question:"What type of engine is commonly used in modern commercial aircraft?", options:["High-bypass turbofan","Turboprop","Turbojet","Ramjet"], answer:"High-bypass turbofan", explanation:"Modern airliners use high-bypass turbofan engines for fuel efficiency and reduced noise." },
  // Hard
  { topic:"Aircraft Systems", difficulty:"hard", type:"mcq", question:"What is the purpose of the bleed air system?", options:["Cabin pressurization, de-icing, and engine starting","Engine cooling only","Fuel pressurization","Landing gear operation"], answer:"Cabin pressurization, de-icing, and engine starting", explanation:"Bleed air from engine compressors is used for pressurization, anti-ice, and pneumatic starting." },
  { topic:"Aircraft Systems", difficulty:"hard", type:"truefalse", question:"Fly-by-wire systems use mechanical cables to transmit pilot inputs to control surfaces.", answer:"False", explanation:"Fly-by-wire uses electronic signals (not cables) to transmit control inputs to actuators." },
  { topic:"Aircraft Systems", difficulty:"hard", type:"mcq", question:"In a glass cockpit, what does the PFD display?", options:["Primary flight instruments (attitude, speed, altitude, heading)","Engine parameters","Navigation map","Weather radar"], answer:"Primary flight instruments (attitude, speed, altitude, heading)", explanation:"The PFD shows essential flight data: attitude, airspeed, altitude, heading, and vertical speed." },
  { topic:"Aircraft Systems", difficulty:"hard", type:"short", question:"What is the purpose of a yaw damper?", answer:"To automatically counteract Dutch roll oscillations", explanation:"The yaw damper detects and dampens Dutch roll, which is a combined yaw-roll oscillation." },

  // ═══════════════════════════════════════════
  // FLIGHT PLANNING
  // ═══════════════════════════════════════════
  // Easy
  { topic:"Flight Planning", difficulty:"easy", type:"mcq", question:"What is the term 'V1' in aviation?", options:["Takeoff decision speed","Landing speed","Stall speed","Cruising speed"], answer:"Takeoff decision speed", explanation:"V1 is the speed beyond which the takeoff can no longer be safely aborted." },
  { topic:"Flight Planning", difficulty:"easy", type:"mcq", question:"What does ATIS provide?", options:["Weather and airport information","Flight plans","ATC clearances","Radar vectors"], answer:"Weather and airport information", explanation:"ATIS broadcasts current weather, active runway, and other airport information." },
  { topic:"Flight Planning", difficulty:"easy", type:"truefalse", question:"Fuel planning must include reserve fuel for every flight.", answer:"True", explanation:"Regulations require carrying reserve/contingency fuel beyond the trip fuel requirement." },
  { topic:"Flight Planning", difficulty:"easy", type:"short", question:"What is the speed called at which an aircraft becomes airborne?", answer:"Rotation speed (Vr)", explanation:"Vr is the speed at which the pilot pulls back on the controls to rotate and lift off." },
  { topic:"Flight Planning", difficulty:"easy", type:"mcq", question:"What document must a pilot file before an IFR flight?", options:["Flight plan","Maintenance log","Weight manifest","Insurance certificate"], answer:"Flight plan", explanation:"A flight plan must be filed with ATC before conducting an IFR flight." },
  { topic:"Flight Planning", difficulty:"easy", type:"truefalse", question:"Headwinds increase fuel consumption on a flight.", answer:"True", explanation:"Headwinds reduce ground speed, increasing flight time and thus fuel consumption." },
  // Medium
  { topic:"Flight Planning", difficulty:"medium", type:"mcq", question:"What is the difference between TAS and GS?", options:["Wind component","Altitude","Temperature","Pressure"], answer:"Wind component", explanation:"Ground Speed = True Airspeed ± wind component. Wind is the difference between TAS and GS." },
  { topic:"Flight Planning", difficulty:"medium", type:"mcq", question:"Which V-speed represents the best rate of climb?", options:["Vy","Vx","Va","Vne"], answer:"Vy", explanation:"Vy gives the best rate of climb (most altitude gained per unit time)." },
  { topic:"Flight Planning", difficulty:"medium", type:"truefalse", question:"The alternate airport fuel requirement for IFR flights is typically 45 minutes of flying.", answer:"True", explanation:"IFR flights typically require enough fuel to fly to the alternate plus 45 minutes reserve." },
  { topic:"Flight Planning", difficulty:"medium", type:"mcq", question:"What does the 1-in-60 rule relate to in navigation?", options:["Track error and distance off track","Fuel calculation","Weight and balance","Engine performance"], answer:"Track error and distance off track", explanation:"The 1-in-60 rule: 1° off track = 1 NM deviation per 60 NM traveled." },
  { topic:"Flight Planning", difficulty:"medium", type:"short", question:"What is the name of the speed that must never be exceeded in flight?", answer:"Vne (Velocity Never Exceed)", explanation:"Vne is the maximum speed the aircraft structure is designed to withstand." },
  { topic:"Flight Planning", difficulty:"medium", type:"mcq", question:"What is the purpose of a load sheet?", options:["Document aircraft weight and balance","Check engine performance","Record fuel uplifted","Plan the route"], answer:"Document aircraft weight and balance", explanation:"The load sheet records weights and CG position to ensure the aircraft is within limits." },
  // Hard
  { topic:"Flight Planning", difficulty:"hard", type:"mcq", question:"What is the critical engine on a multi-engine aircraft?", options:["The engine whose failure most adversely affects performance/handling","The left engine always","The newest engine","The engine with most thrust"], answer:"The engine whose failure most adversely affects performance/handling", explanation:"The critical engine's failure causes the most asymmetric thrust and control difficulty." },
  { topic:"Flight Planning", difficulty:"hard", type:"truefalse", question:"Cost Index is the ratio of time-related costs to fuel costs.", answer:"True", explanation:"Cost Index = time cost / fuel cost. Higher CI = faster speed; lower CI = more fuel-efficient." },
  { topic:"Flight Planning", difficulty:"hard", type:"mcq", question:"What is the significance of the ETOPS diversion time?", options:["Maximum time from a suitable diversion airport","Flight duration limit","Fuel endurance","Crew duty time"], answer:"Maximum time from a suitable diversion airport", explanation:"ETOPS allows twin-engine planes to fly routes if within a specified time from a diversion airport." },
  { topic:"Flight Planning", difficulty:"hard", type:"short", question:"What is the formula for calculating Top of Descent (TOD)?", answer:"TOD = (Cruise altitude - Airport elevation) / 300 × ground speed factor", explanation:"A common rule: (altitude to lose in hundreds of feet) × 3 = distance in NM to start descent." },

  // ═══════════════════════════════════════════
  // RADIO AIDS & COMMUNICATION
  // ═══════════════════════════════════════════
  // Easy
  { topic:"Radio Aids", difficulty:"easy", type:"mcq", question:"What does VHF stand for?", options:["Very High Frequency","Very Heavy Fuel","Variable Height Finder","Visual Heading Frequency"], answer:"Very High Frequency", explanation:"VHF = Very High Frequency, the primary radio band for aviation communication." },
  { topic:"Radio Aids", difficulty:"easy", type:"truefalse", question:"VHF communication is limited to line-of-sight range.", answer:"True", explanation:"VHF signals travel in straight lines and are limited by the curvature of the Earth." },
  { topic:"Radio Aids", difficulty:"easy", type:"mcq", question:"What is the international emergency frequency?", options:["121.5 MHz","118.0 MHz","125.0 MHz","119.1 MHz"], answer:"121.5 MHz", explanation:"121.5 MHz is the international VHF emergency/distress frequency." },
  { topic:"Radio Aids", difficulty:"easy", type:"short", question:"What does the word 'Mayday' signify in aviation?", answer:"A distress call indicating grave and imminent danger", explanation:"Mayday (from French 'm'aidez') signals a life-threatening emergency requiring immediate assistance." },
  { topic:"Radio Aids", difficulty:"easy", type:"mcq", question:"What does the phonetic alphabet letter 'A' stand for?", options:["Alpha","Able","Apple","Ace"], answer:"Alpha", explanation:"In the ICAO phonetic alphabet, A = Alpha." },
  { topic:"Radio Aids", difficulty:"easy", type:"truefalse", question:"The word 'Roger' means the pilot agrees with the instruction.", answer:"False", explanation:"'Roger' means 'I have received your message,' not that you agree or will comply." },
  // Medium
  { topic:"Radio Aids", difficulty:"medium", type:"mcq", question:"What is the purpose of an ILS?", options:["Precision approach guidance in poor visibility","En-route navigation","Engine monitoring","Communication with tower"], answer:"Precision approach guidance in poor visibility", explanation:"ILS provides lateral (localizer) and vertical (glide slope) guidance for precision approaches." },
  { topic:"Radio Aids", difficulty:"medium", type:"mcq", question:"An ILS consists of which two components?", options:["Localizer and Glide Slope","VOR and DME","GPS and INS","NDB and ADF"], answer:"Localizer and Glide Slope", explanation:"The localizer provides lateral guidance; the glide slope provides vertical descent path guidance." },
  { topic:"Radio Aids", difficulty:"medium", type:"truefalse", question:"HF radio can be used for long-distance communication over oceans.", answer:"True", explanation:"HF radio waves reflect off the ionosphere, enabling long-range communication beyond VHF line-of-sight." },
  { topic:"Radio Aids", difficulty:"medium", type:"mcq", question:"What does 'Pan-Pan' signify?", options:["Urgency condition","Distress condition","Normal communication","Ground handling request"], answer:"Urgency condition", explanation:"Pan-Pan indicates an urgency (serious but not immediately life-threatening) condition." },
  { topic:"Radio Aids", difficulty:"medium", type:"short", question:"What does ADF stand for?", answer:"Automatic Direction Finder", explanation:"ADF is a receiver that determines the bearing to an NDB ground station." },
  { topic:"Radio Aids", difficulty:"medium", type:"mcq", question:"What frequency band does a Mode S transponder operate on?", options:["1030/1090 MHz","121.5 MHz","108-118 MHz","243 MHz"], answer:"1030/1090 MHz", explanation:"Mode S transponders receive on 1030 MHz and reply on 1090 MHz." },
  // Hard
  { topic:"Radio Aids", difficulty:"hard", type:"mcq", question:"What is the standard ILS glide slope angle?", options:["3 degrees","5 degrees","2 degrees","4 degrees"], answer:"3 degrees", explanation:"The standard ILS glide slope is 3° (approximately 300 ft per NM)." },
  { topic:"Radio Aids", difficulty:"hard", type:"truefalse", question:"GBAS (Ground-Based Augmentation System) enhances GPS accuracy for precision approaches.", answer:"True", explanation:"GBAS provides local GPS corrections for CAT I/II/III precision approaches." },
  { topic:"Radio Aids", difficulty:"hard", type:"mcq", question:"What is the decision height for a CAT IIIa ILS approach?", options:["Below 100 ft or no DH","200 ft","300 ft","500 ft"], answer:"Below 100 ft or no DH", explanation:"CAT IIIa has DH below 100 ft (or none), with RVR not less than 200m." },
  { topic:"Radio Aids", difficulty:"hard", type:"short", question:"What technology is replacing ILS for precision approaches at many airports?", answer:"GLS (GBAS Landing System)", explanation:"GLS uses GPS with ground-based augmentation for precision approach guidance." },

  // ═══════════════════════════════════════════
  // AVIATION SAFETY
  // ═══════════════════════════════════════════
  // Easy
  { topic:"Aviation Safety", difficulty:"easy", type:"mcq", question:"What does the 'sterile cockpit' rule require?", options:["No non-essential conversation below 10,000 ft","Cockpit must be cleaned","Only the captain can speak","No eating in the cockpit"], answer:"No non-essential conversation below 10,000 ft", explanation:"The sterile cockpit rule prohibits non-essential activities during critical phases of flight." },
  { topic:"Aviation Safety", difficulty:"easy", type:"truefalse", question:"A black box is actually orange in color.", answer:"True", explanation:"Flight recorders are painted bright orange/red for easy recovery, despite the name 'black box'." },
  { topic:"Aviation Safety", difficulty:"easy", type:"mcq", question:"What aviation event reporting system encourages voluntary safety reports?", options:["ASRS/Confidential reporting","Black box analysis","Weather reports","ATC recordings"], answer:"ASRS/Confidential reporting", explanation:"Aviation Safety Reporting System allows confidential reporting of safety concerns without penalty." },
  { topic:"Aviation Safety", difficulty:"easy", type:"short", question:"What does CRM stand for in aviation safety?", answer:"Crew Resource Management", explanation:"CRM focuses on communication, leadership, and decision-making skills in the cockpit." },
  { topic:"Aviation Safety", difficulty:"easy", type:"mcq", question:"What is the purpose of the Safety Management System (SMS)?", options:["Systematically manage safety risks","Manage crew schedules","Handle passenger complaints","Track maintenance costs"], answer:"Systematically manage safety risks", explanation:"SMS provides a systematic approach to managing safety, including policies, risk management, and assurance." },
  { topic:"Aviation Safety", difficulty:"easy", type:"truefalse", question:"Bird strikes are most common during takeoff and landing phases.", answer:"True", explanation:"Most bird strikes occur below 3,000 ft AGL during takeoff, approach, and landing." },
  // Medium
  { topic:"Aviation Safety", difficulty:"medium", type:"mcq", question:"What does CFIT stand for?", options:["Controlled Flight Into Terrain","Certified Flight Instructor Training","Continuous Fuel Injection Technology","Crew Fatigue Indicator Tool"], answer:"Controlled Flight Into Terrain", explanation:"CFIT occurs when an airworthy aircraft is flown into terrain/water without loss of control." },
  { topic:"Aviation Safety", difficulty:"medium", type:"mcq", question:"GPWS/EGPWS primarily protects against which hazard?", options:["CFIT (Controlled Flight Into Terrain)","Engine failure","Icing","Turbulence"], answer:"CFIT (Controlled Flight Into Terrain)", explanation:"EGPWS uses terrain databases and radar altimetry to warn pilots of terrain proximity." },
  { topic:"Aviation Safety", difficulty:"medium", type:"truefalse", question:"Hypoxia can occur at cabin altitudes above 10,000 ft without supplemental oxygen.", answer:"True", explanation:"Above 10,000 ft, reduced oxygen partial pressure can cause hypoxia symptoms." },
  { topic:"Aviation Safety", difficulty:"medium", type:"short", question:"What is the Swiss Cheese Model in aviation safety?", answer:"A model showing how multiple layers of defenses have holes that can align to cause an accident", explanation:"James Reason's Swiss Cheese Model illustrates how accidents result from aligned failures in multiple barriers." },
  { topic:"Aviation Safety", difficulty:"medium", type:"mcq", question:"What does IMSAFE stand for in pilot self-assessment?", options:["Illness, Medication, Stress, Alcohol, Fatigue, Emotion","Instruments, Maps, Speed, Altitude, Fuel, Engine","International, Medical, Safety, Aviation, Flight, Emergency","None of the above"], answer:"Illness, Medication, Stress, Alcohol, Fatigue, Emotion", explanation:"IMSAFE is a personal checklist pilots use to assess their fitness to fly." },
  { topic:"Aviation Safety", difficulty:"medium", type:"mcq", question:"What is the minimum rest period for a pilot between duty periods (typical regulation)?", options:["10 hours","6 hours","8 hours","12 hours"], answer:"10 hours", explanation:"Most regulations require a minimum 10-hour rest period, including 8 hours of uninterrupted sleep." },
  // Hard
  { topic:"Aviation Safety", difficulty:"hard", type:"mcq", question:"In the Threat and Error Management (TEM) model, what are the three components?", options:["Threats, Errors, Undesired Aircraft States","Risk, Hazard, Accident","Human, Machine, Environment","Pilot, Controller, Dispatcher"], answer:"Threats, Errors, Undesired Aircraft States", explanation:"TEM framework: manage threats → prevent errors → recover from undesired aircraft states." },
  { topic:"Aviation Safety", difficulty:"hard", type:"truefalse", question:"A runway incursion is defined as any occurrence involving an unauthorized aircraft, vehicle, or person on a runway.", answer:"True", explanation:"ICAO defines runway incursion as any occurrence at an aerodrome involving incorrect presence on a runway." },
  { topic:"Aviation Safety", difficulty:"hard", type:"mcq", question:"What is the purpose of an ELT (Emergency Locator Transmitter)?", options:["Transmit distress signal after a crash","Record flight data","Communicate with ATC","Detect turbulence"], answer:"Transmit distress signal after a crash", explanation:"ELTs activate on impact and transmit on 121.5 MHz and 406 MHz to aid search and rescue." },
  { topic:"Aviation Safety", difficulty:"hard", type:"short", question:"What is the 'dirty dozen' in aviation maintenance safety?", answer:"12 common human factors that lead to maintenance errors", explanation:"The Dirty Dozen includes: lack of communication, distraction, lack of resources, stress, complacency, lack of teamwork, pressure, lack of awareness, lack of knowledge, fatigue, lack of assertiveness, and norms." },

  // ═══════════════════════════════════════════
  // GENERAL KNOWLEDGE
  // ═══════════════════════════════════════════
  // Easy
  { topic:"General Knowledge", difficulty:"easy", type:"mcq", question:"Who are credited with the first powered flight?", options:["Wright Brothers","Leonardo da Vinci","Charles Lindbergh","Amelia Earhart"], answer:"Wright Brothers", explanation:"Orville and Wilbur Wright achieved the first sustained powered flight on Dec 17, 1903, at Kitty Hawk." },
  { topic:"General Knowledge", difficulty:"easy", type:"mcq", question:"What is the busiest airport in the world by passenger traffic?", options:["Hartsfield-Jackson Atlanta (ATL)","Dubai (DXB)","London Heathrow (LHR)","Beijing Capital (PEK)"], answer:"Hartsfield-Jackson Atlanta (ATL)", explanation:"ATL has been the world's busiest airport by passenger numbers for many years." },
  { topic:"General Knowledge", difficulty:"easy", type:"truefalse", question:"The Airbus A380 is a double-deck, wide-body aircraft.", answer:"True", explanation:"The A380 is the world's largest commercial passenger jet with a full-length double deck." },
  { topic:"General Knowledge", difficulty:"easy", type:"short", question:"What is the NATO phonetic alphabet letter for 'B'?", answer:"Bravo", explanation:"In the ICAO/NATO phonetic alphabet, B = Bravo." },
  { topic:"General Knowledge", difficulty:"easy", type:"mcq", question:"What does the Boeing 737 represent?", options:["World's best-selling commercial jet","A military fighter","A cargo-only aircraft","A supersonic transport"], answer:"World's best-selling commercial jet", explanation:"The Boeing 737 is the best-selling commercial jetliner in aviation history." },
  { topic:"General Knowledge", difficulty:"easy", type:"truefalse", question:"The speed of sound at sea level is approximately Mach 1 or 661 knots.", answer:"True", explanation:"At sea level (15°C), the speed of sound is about 661 knots (340 m/s), defined as Mach 1." },
  // Medium
  { topic:"General Knowledge", difficulty:"medium", type:"mcq", question:"What type of aircraft is a Cessna 172?", options:["Single-engine, high-wing piston aircraft","Twin-engine turboprop","Business jet","Helicopter"], answer:"Single-engine, high-wing piston aircraft", explanation:"The Cessna 172 Skyhawk is the most popular flight training aircraft ever manufactured." },
  { topic:"General Knowledge", difficulty:"medium", type:"mcq", question:"What is wake turbulence?", options:["Disturbed air left behind a flying aircraft","Turbulence from thunderstorms","Rough air near mountains","Jet stream turbulence"], answer:"Disturbed air left behind a flying aircraft", explanation:"Wake turbulence consists of wingtip vortices and is most dangerous behind heavy aircraft." },
  { topic:"General Knowledge", difficulty:"medium", type:"truefalse", question:"The Concorde was a supersonic commercial aircraft that cruised at Mach 2.", answer:"True", explanation:"The Concorde cruised at Mach 2.04 (about 1,354 mph), retiring in 2003." },
  { topic:"General Knowledge", difficulty:"medium", type:"short", question:"What is the 'angle of attack' in aerodynamics?", answer:"The angle between the wing chord line and the relative wind", explanation:"Angle of attack determines lift; exceeding the critical AoA causes a stall." },
  { topic:"General Knowledge", difficulty:"medium", type:"mcq", question:"What are the four forces acting on an aircraft in flight?", options:["Lift, Weight, Thrust, Drag","Speed, Altitude, Heading, Fuel","Pitch, Roll, Yaw, Thrust","Lift, Wind, Power, Gravity"], answer:"Lift, Weight, Thrust, Drag", explanation:"The four fundamental forces: Lift (up), Weight (down), Thrust (forward), Drag (backward)." },
  { topic:"General Knowledge", difficulty:"medium", type:"mcq", question:"What causes a wing to stall?", options:["Exceeding the critical angle of attack","Flying too fast","Engine failure","Running out of fuel"], answer:"Exceeding the critical angle of attack", explanation:"A stall occurs when the critical angle of attack is exceeded, disrupting smooth airflow over the wing." },
  // Hard
  { topic:"General Knowledge", difficulty:"hard", type:"mcq", question:"What is the primary purpose of winglets on modern aircraft?", options:["Reduce induced drag and improve fuel efficiency","Increase maximum speed","Improve low-speed handling","Aid in navigation"], answer:"Reduce induced drag and improve fuel efficiency", explanation:"Winglets reduce wingtip vortices, cutting induced drag by 3-5% and improving fuel efficiency." },
  { topic:"General Knowledge", difficulty:"hard", type:"truefalse", question:"Bernoulli's principle alone fully explains how wings generate lift.", answer:"False", explanation:"Lift is explained by both Bernoulli's principle (pressure differential) and Newton's third law (deflection of air downward)." },
  { topic:"General Knowledge", difficulty:"hard", type:"mcq", question:"What is the service ceiling of a typical commercial jet like the Boeing 777?", options:["43,100 ft","55,000 ft","30,000 ft","50,000 ft"], answer:"43,100 ft", explanation:"The Boeing 777-200 has a service ceiling of approximately 43,100 ft." },
  { topic:"General Knowledge", difficulty:"hard", type:"short", question:"What phenomenon causes 'Dutch roll' in swept-wing aircraft?", answer:"Coupling of yaw and roll oscillations due to swept wing design", explanation:"Dutch roll is a combined yaw-roll oscillation common in swept-wing aircraft, controlled by yaw dampers." }
];

// Get unique topics
const AVAILABLE_TOPICS = [...new Set(QUESTION_BANK.map(q => q.topic))];
